### ISSUE TITLE
Prophet model not showing anything for dates after 1999

### ISSUE THREAD

**Issue by aswerve97** [aswerve97/US_Population#5]
If you start from 1995 to 2010, there is some data on the chart, any number greater then or equal to 1999 breaks it
<img width="1358" alt="Screen Shot 2022-01-20 at 2 12 27 AM" src="https://user-images.githubusercontent.com/74816568/150290736-5f451a4d-2c1b-4b45-8516-bcadaf0c12c8.png">
s

**Comment by GrissomE** [comment]
Model isn't returning correct data, 
![image](https://user-images.githubusercontent.com/11250870/150390389-15daf9c4-c95e-45af-a902-923da604de07.png)
Only returns value for 1999 when calling the prophet_predict function. 


Model bounds appear to be incorrect, dataset its iterating over doesn't include anything >1999 which explains why its only displaying that datapoint
![image](https://user-images.githubusercontent.com/11250870/150390944-21a55a71-9f9f-436d-b320-efdff122ab94.png)

**Comment by GrissomE** [comment]
It seems the model's dataset only runs to 1981 so it forecasts the number of periods (2018-1999) after 1981,

**Comment by aswerve97** [comment]
This is a problem that stems with how the model is trained. Once the model is trained and the model is saved, it performs really well on the data it was trained on. It will not perform that well on data it has not seen. I think I may go back and retrain the model on all the data we have instead and let it acutally guess on later data
